"""empty message

Revision ID: 0238a5ea7fba
Revises: 7d7cef9916aa
Create Date: 2026-02-17 15:43:45.790942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0238a5ea7fba'
down_revision = '7d7cef9916aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
