"""empty message

Revision ID: 70e927344105
Revises: 9dbb22679f3d
Create Date: 2026-02-26 08:22:09.108089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70e927344105'
down_revision = '9dbb22679f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_chat_pair', ['user_id', 'coach_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_constraint('unique_chat_pair', type_='unique')

    # ### end Alembic commands ###
