"""empty message

Revision ID: 77e4e2aa47f8
Revises: caf2f44af0ff
Create Date: 2026-02-16 09:47:13.438569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e4e2aa47f8'
down_revision = 'caf2f44af0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.drop_column('profile_image')
        batch_op.drop_column('phone')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###
