"""empty message

Revision ID: 7dffbc214d24
Revises: aebfae71bf36
Create Date: 2026-02-09 12:13:41.912904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dffbc214d24'
down_revision = 'aebfae71bf36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('coach_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('coach_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
