"""empty message

Revision ID: 8d4d8a8e0a5d
Revises: 530f1b061af7
Create Date: 2026-02-02 10:20:15.302454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4d8a8e0a5d'
down_revision = '530f1b061af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('course_coach_id_fkey'), type_='foreignkey')
        batch_op.drop_column('coach_id')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('message_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('message_coach_id_fkey'), type_='foreignkey')
        batch_op.drop_column('coach_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('message_coach_id_fkey'), 'coach', ['coach_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('message_user_id_fkey'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('course_coach_id_fkey'), 'coach', ['coach_id'], ['id'])

    # ### end Alembic commands ###
