"""empty message

Revision ID: a58455e10289
Revises: 0ba43055aa76
Create Date: 2026-02-19 15:57:56.001757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a58455e10289'
down_revision = '0ba43055aa76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coach', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('province')

    # ### end Alembic commands ###
