"""empty message

Revision ID: a62df03444f3
Revises: 284a32289c4b
Create Date: 2026-02-13 15:31:30.054478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62df03444f3'
down_revision = '284a32289c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('coach_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('coach_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
