"""empty message

Revision ID: afc9bbd91286
Revises: 999921d33841
Create Date: 2026-02-26 07:45:18.824278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc9bbd91286'
down_revision = '999921d33841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_constraint(batch_op.f('message_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('message_coach_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('coach_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('message_coach_id_fkey'), 'coach', ['coach_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('message_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
